apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubewise-{{ .Release.Name }}-agent-credentials
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/app: kubewise-{{ .Release.Name }}-k8s-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
stringData:
  KUBEWISE_CLUSTER_ID: {{ required "The Kubewise cluster ID is requered." .Values.credentials.clusterId | quote }}
  KUBEWISE_API_KEY: {{ required "The Kubewise cluster API key is requered." .Values.credentials.apiKey | quote }}