apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubewise-{{ .Release.Name }}-agent-credentials
  labels:
    kubewise.io/group: k8s
    kubewise.io/app: k8s-agent
stringData:
  KUBEWISE_CLUSTER_ID: {{ required "The Kubewise cluster ID is requered." .Values.credentials.clusterId | quote }}
  KUBEWISE_API_KEY: {{ required "The Kubewise cluster API key is requered." .Values.credentials.apiKey | quote }}