---
#
# Cluster role for the K8s agent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubewise-{{ .Release.Name }}-k8s-agent
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/app: kubewise-{{ .Release.Name }}-k8s-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubewise.io/group: k8s
    kubewise.io/app: k8s-agent
rules:
- apiGroups: [""]
  resources: ["nodes","namespaces","services","pods","pods/log", "events"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["daemonsets","deployments","replicasets","statefulsets"]
  verbs: ["get","watch","list"]
- apiGroups: ["batch"]
  resources: ["cronjobs","jobs"]
  verbs: ["get","watch","list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get","watch","list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses","networkpolicies"]
  verbs: ["get","watch","list"]
- apiGroups: ["aquasecurity.github.io"]
  resources: ["clustercompliancereports","clusterconfigauditreports","clusterinfraassessmentreports","clusterrbacassessmentreports","clustersbomreports","clustervulnerabilityreports","configauditreports","exposedsecretreports","infraassessmentreports","rbacassessmentreports","sbomreports","vulnerabilityreports"]
  verbs: ["get","watch","list"]

---
#
# Service account for the K8s agent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewise-{{ .Release.Name }}-k8s-agent
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/app: kubewise-{{ .Release.Name }}-k8s-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubewise.io/group: k8s
    kubewise.io/app: k8s-agent

---
#
# Cluster role binding for the K8s agent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubewise-{{ .Release.Name }}-k8s-agent
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/app: kubewise-{{ .Release.Name }}-k8s-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubewise.io/group: k8s
    kubewise.io/app: k8s-agent
subjects:
- kind: ServiceAccount
  name: kubewise-{{ .Release.Name }}-k8s-agent
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewise-{{ .Release.Name }}-k8s-agent