---
kind: Service
apiVersion: v1
metadata:
  name: kubewise-{{ .Release.Name }}-k8s-agent-sts
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/app: kubewise-{{ .Release.Name }}-k8s-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubewise.io/type: agent
    kubewise.io/group: kubernetes
    kubewise.io/app: k8s-agent
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/app: kubewise-{{ .Release.Name }}-k8s-agent
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubewise.io/type: agent
    kubewise.io/group: kubernetes
    kubewise.io/app: k8s-agent
  ports: []
